name: Docker App Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout release
      uses: actions/checkout@v3

    - name: archive oh-mall-backend
      run: tar cvfz ./oh-mall-backend.tar.gz *

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./oh-mall-backend.tar.gz s3://oh-mall-bucket/oh-mall-folder/

    - name: deploy with AWS codeDeploy
      run: aws deploy --region ap-northeast-2 create-deployment
        --application-name oh-mall-backend
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name oh-mall-backend-group
        --s3-location bucket=oh-mall-bucket,bundleType=tgz,key=oh-mall-folder/oh-mall-backend.tar.gz
        
